{
 "title": "Kruize Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Kruize Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"kruize-recommendations-[^-]*-[^-]*$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kruize Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Kruize CPU Requests (per instance)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",pod=~\"kruize-recommendations-[^-]*-[^-]*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kruize CPU Limits (per instance)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\",pod=~\"kruize-recommendations-[^-]*-[^-]*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kruize Memory Requests (in MB per instance)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\",pod=~\"kruize-recommendations-[^-]*-[^-]*\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kruize Memory Limits (in MB per instance)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\",pod=~\"kruize-recommendations-[^-]*-[^-]*\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"kruize-recommendations-[^-]*-[^-]*$\"}[1m]))",
     "legendFormat": "kruize-recommendations total CPU usage"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"kruize-recommendations-[^-]*-[^-]*$\"}[1m]))",
     "legendFormat": "kruize-recommendations total CPU throttled"
    }
   ]
  },
  {
   "title": "Memory Usage (in MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"kruize-recommendations-[^-]*-[^-]*$\"}) / 1024 / 1024",
     "legendFormat": "kruize-recommendations total memory usage (in MB)"
    }
   ]
  },
  {
   "title": "Kruize API Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time (in s) taken by api updateRecommendations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max(max_over_time(kruizeAPI_max{api=\"updateRecommendations\",status=\"success\"}[1m]))",
     "legendFormat": "Max perAPIcall in last 1m"
    },
    {
     "expr": "sum(increase(kruizeAPI_sum{api=\"updateRecommendations\",status=\"success\"}[1m])) / sum(increase(kruizeAPI_count{api=\"updateRecommendations\",status=\"success\"}[1m]))",
     "legendFormat": "Avg perAPIcall in last 1m"
    }
   ]
  },
  {
   "title": "No.of calls to api  updateRecommendations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(kruizeAPI_count{api=\"updateRecommendations\"}[1m])) by (api,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total calls to api  updateRecommendations for an interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(kruizeAPI_count{api=\"updateRecommendations\"}[$__range])) by (api,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time (in s) taken by api updateResults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "max(max_over_time(kruizeAPI_max{api=\"updateResults\",status=\"success\"}[1m]))",
     "legendFormat": "Max perAPIcall in last 1m"
    },
    {
     "expr": "sum(increase(kruizeAPI_sum{api=\"updateResults\",status=\"success\"}[1m])) / sum(increase(kruizeAPI_count{api=\"updateResults\",status=\"success\"}[1m]))",
     "legendFormat": "Avg perAPIcall in last 1m"
    }
   ]
  },
  {
   "title": "No.of calls to api  updateResults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(kruizeAPI_count{api=\"updateResults\"}[1m])) by (api,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No.of calls to api  updateResults for an interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(kruizeAPI_count{api=\"updateResults\"}[$__range])) by (api,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kruize DB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time (in s) taken by method  addBulkResultsToDBAndFetchFailedResults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "max(max_over_time(kruizeDB_max{method=\"addBulkResultsToDBAndFetchFailedResults\",status=\"success\"}[1m]))",
     "legendFormat": "Max perAPIcall in last 1m"
    },
    {
     "expr": "sum(increase(kruizeDB_sum{method=\"addBulkResultsToDBAndFetchFailedResults\",status=\"success\"}[1m])) / sum(increase(kruizeDB_count{method=\"addBulkResultsToDBAndFetchFailedResults\",status=\"success\"}[1m]))",
     "legendFormat": "Avg perAPIcall in last 1m"
    }
   ]
  },
  {
   "title": "No.of calls to method  addBulkResultsToDBAndFetchFailedResults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(kruizeDB_count{method=\"addBulkResultsToDBAndFetchFailedResults\",status=\"success\"}[1m])) by (method, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time (in s) taken by method  loadResultsByExperimentName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "max(max_over_time(kruizeDB_max{method=\"loadResultsByExperimentName\",status=\"success\"}[1m]))",
     "legendFormat": "Max perAPIcall in last 1m"
    },
    {
     "expr": "sum(increase(kruizeDB_sum{method=\"loadResultsByExperimentName\",status=\"success\"}[1m])) / sum(increase(kruizeDB_count{method=\"loadResultsByExperimentName\",status=\"success\"}[1m]))",
     "legendFormat": "Avg perAPIcall in last 1m"
    }
   ]
  },
  {
   "title": "No.of calls to method  loadResultsByExperimentName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(kruizeDB_count{method=\"loadResultsByExperimentName\"}[1m])) by (method,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time (in s) taken by method  addRecommendationToDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "max(max_over_time(kruizeDB_max{method=\"addRecommendationToDB\",status=\"success\"}[1m]))",
     "legendFormat": "Max perAPIcall in last 1m"
    },
    {
     "expr": "sum(increase(kruizeDB_sum{method=\"addRecommendationToDB\",status=\"success\"}[1m])) / sum(increase(kruizeDB_count{method=\"addRecommendationToDB\",status=\"success\"}[1m]))",
     "legendFormat": "Avg perAPIcall in last 1m"
    }
   ]
  },
  {
   "title": "No.of calls to method  addRecommendationToDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(increase(kruizeDB_count{method=\"addRecommendationToDB\"}[1m])) by (method,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ROS SPECIFICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "free_storage_space_average (in MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{job=~\"cloudwatch-exporter.*\",dbinstance_identifier=\"kruize-prod\"} / 1024 / 1024",
     "legendFormat": "kruize-prod"
    }
   ]
  },
  {
   "title": "kafka lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{group=\"ros-ocp\", topic=\"hccm.ros.events\"} > 0)",
     "legendFormat": "kruize-prod"
    }
   ]
  },
  { "title": "DB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Time (in s) taken by method  loadExperimentByName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "max(max_over_time(kruizeDB_max{method=\"loadExperimentByName\",status=\"success\"}[1m]))",
     "legendFormat": "Max perAPIcall in last 1m"
    },
    {
     "expr": "sum(increase(kruizeDB_sum{method=\"loadExperimentByName\",status=\"success\"}[1m])) / sum(increase(kruizeDB_count{method=\"loadExperimentByName\",status=\"success\"}[1m]))",
     "legendFormat": "Avg perAPIcall in last 1m"
    }
   ]
  },
  {
   "title": "No.of calls to method  loadExperimentByName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "sum(increase(kruizeDB_count{method=\"loadExperimentByName\",status=\"success\"}[1m])) by (method,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time (in s) taken by method  loadRecommendationsByExperimentNameAndDate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "max(max_over_time(kruizeDB_max{method=\"loadRecommendationsByExperimentNameAndDate\",status=\"success\"}[1m]))",
     "legendFormat": "Max perAPIcall in last 1m"
    },
    {
     "expr": "sum(increase(kruizeDB_sum{method=\"loadRecommendationsByExperimentNameAndDate\",status=\"success\"}[1m])) / sum(increase(kruizeDB_count{method=\"loadRecommendationsByExperimentNameAndDate\",status=\"success\"}[1m]))",
     "legendFormat": "Avg perAPIcall in last 1m"
    }
   ]
  },
  {
   "title": "No.of calls to method  loadRecommendationsByExperimentNameAndDate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum(increase(kruizeDB_count{method=\"loadRecommendationsByExperimentNameAndDate\",status=\"success\"}[1m])) by (method,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time (in s) taken by method  addExperimentToDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "max(max_over_time(kruizeDB_max{method=\"addExperimentToDB\",status=\"success\"}[1m]))",
     "legendFormat": "Max perAPIcall in last 1m"
    },
    {
     "expr": "sum(increase(kruizeDB_sum{method=\"addExperimentToDB\",status=\"success\"}[1m])) / sum(increase(kruizeDB_count{method=\"addExperimentToDB\",status=\"success\"}[1m]))",
     "legendFormat": "Avg perAPIcall in last 1m"
    }
   ]
  },
  {
   "title": "No.of calls to method  addExperimentToDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "sum(increase(kruizeDB_count{method=\"addExperimentToDB\"}[1m])) by (method,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Time (in s) taken by api createExperiment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "max(max_over_time(kruizeAPI_max{api=\"createExperiment\",status=\"success\"}[1m]))",
     "legendFormat": "Max perAPIcall in last 1m"
    },
    {
     "expr": "sum(increase(kruizeAPI_sum{api=\"createExperiment\",status=\"success\"}[1m])) / sum(increase(kruizeAPI_count{api=\"createExperiment\",status=\"success\"}[1m]))",
     "legendFormat": "Avg perAPIcall in last 1m"
    }
   ]
  },
  {
   "title": "No.of calls to api  createExperiment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "sum(increase(kruizeAPI_count{api=\"createExperiment\"}[1m])) by (api,status)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "network_receive_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"kruize-recommendations-[^-]*-[^-]*$\"}[1m]))",
       "legendFormat": "kruize-recommendations"
      }
     ]
    },
    {
     "title": "network_transmit_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"kruize-recommendations-[^-]*-[^-]*$\"}[1m]))",
       "legendFormat": "kruize-recommendations"
      }
     ]
    }
   ]
  },
  {
   "title": "Kruize Metrics for all pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max time (in s) taken by DB methods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "max by(method) (kruizeDB_max{status=\"success\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max time (in s) taken by Kruize api's",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "targets": [
      {
       "expr": "max(max_over_time(kruizeAPI_max{status=\"success\"}[1m])) by (api)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Individual CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 125 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"kruize-recommendations-[^-]*-[^-]*$\"}[1m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Individual Memory Usage (in MB)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 134 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"kruize-recommendations-[^-]*-[^-]*$\"}) by (pod) / 1024 / 1024",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentile of time (in s) taken by API updateRecommendations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "quantile(1, rate(kruizeAPI_sum{api=\"updateRecommendations\", status=\"success\"}[24h]))",
       "legendFormat": "100th percentile"
      },
      {
       "expr": "quantile(0.95, rate(kruizeAPI_sum{api=\"updateRecommendations\", status=\"success\"}[24h]))",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "quantile(0.75, rate(kruizeAPI_sum{api=\"updateRecommendations\", status=\"success\"}[24h]))",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "quantile(0.5, rate(kruizeAPI_sum{api=\"updateRecommendations\", status=\"success\"}[24h]))",
       "legendFormat": "50th percentile"
      }
     ]
    },
    {
     "title": "Percentile Data for no.of API calls to updateRecommendations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
     "targets": [
      {
       "expr": "quantile(1, increase(kruizeAPI_count{api=\"updateRecommendations\", status=\"success\"}[24h]))",
       "legendFormat": "100th percentile"
      },
      {
       "expr": "quantile(0.95, increase(kruizeAPI_count{api=\"updateRecommendations\", status=\"success\"}[24h]))",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "quantile(0.75, increase(kruizeAPI_count{api=\"updateRecommendations\", status=\"success\"}[24h]))",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "quantile(0.5, increase(kruizeAPI_count{api=\"updateRecommendations\", status=\"success\"}[24h]))",
       "legendFormat": "50th percentile"
      }
     ]
    }
   ]
  }
 ]
}