name: Regular master commit update check
on:
  schedule:
    - cron: "2 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check change
        run: |
          mkdir -p $PWD/autotune
          git clone --branch master https://github.com/kruize/autotune.git $PWD/autotune
          cd autotune
          git rev-parse --short=7 HEAD >> ../.commitsha
          cd ..
      - name: Do change if the digest changed
        run: |
          git config user.name 'Update-a-Bot'
          git config user.email 'insights@redhat.com'
          git add .baseimagedigest
          git commit -m "chore(master): update and rebuild on new master commit" || echo "No new changes"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'chore(master): update image with new master commit'
